FROM nginx:1.19.2-alpine
COPY images/celeba/celeba-png /usr/share/nginx/images
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.dev /etc/nginx/conf.d
RUN cp /etc/nginx/conf.d/nginx.dev /etc/nginx/conf.d/nginx.conf
