FROM node:14.11.0-alpine3.12 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY app/package.json ./
COPY app/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.3 -g --silent
COPY app ./
RUN npm run build

FROM nginx:1.19.2-alpine
COPY duke /usr/share/nginx/images
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
