version: '3.8'

services:
  db:
    image: postgres
    expose:
      - 5432
  backend:
    build:
      context: ./backend
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
      - db
  images:
    build:
      context: ./frontend
