version: '3.8'

services:
  db:
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
      - POSTGRES_DB=dev_db
  db_data:
    build:
      context: ./backend
      dockerfile: Dockerfile-db_setup
    env_file: ./backend/.env 
    depends_on:
      - db
    command: bash -c "flask db migrate -m \"h\" && flask db upgrade && python populate_db.py"
  backend:
    build:
      dockerfile: Dockerfile-servers.prod
    env_file: ./backend/.env 
    command: gunicorn --bind 0.0.0.0:5000 app:application
    expose:
      - 5000
  frontend:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80

